spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

# mybatis setting
mybatis:
  type-aliases-package: com.project.board.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
